#!/usr/bin/env bash
# Script that redirects the page of a site

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.example.com permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
