#!/usr/bin/env bash
# COnfigures a new Ubuntu machine with custom header

sudo apt-get update
sudo apt-get -y install nginx

sudo allow ufw 'Nginx HTTP'

sudo mkdir -p var/www/html

echo 'Hello World!' |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

sudo sed -i 's#server_name _;#server_name _;\n\n\tlocation /redirect_me {\n\t\tadd_header X-Served-By $hostname;\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}#g' /etc/nginx/sites-available/default
sudo sed -i 's#server_name _;#server_name _;\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t\troot /var/www/html;\n\t\tadd_header Content-Type "text/html";\n\t}\n#g' /etc/nginx/sites-available/default

sudo service nginx restart
