#!/usr/bin/env bash
# This is a bash script that:
# Takes the pid of this process and stores it in /var/run/myscript.pid
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; exit 1' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true; do
	echo "To infinity and beyond indefinitely"
	sleep 2
done
