#!/usr/bin/env bash
# Scripts that prints "Infinity and Beyond" indefinitely with
# two secs sleep, and waits for a sigterm signal
# teminates with "I am invincible"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
	echo "To infinity and beyond indefinitely"
	sleep 2
done
