#!/usr/bin/env bash
# Scripts that changes the IP of local host and facebook

cp /etc/host ~/host.new
echo "127.0.0.2		localhost" > ~/host.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~host.new /etc/host
